In [106]:
import torch
import numpy as np

In [107]:
tensor_1 = torch.Tensor(
    [
        [[1, 2, 3], [5, 4, 7]],
        [[4, 3, 8], [1, 8, 4]],
        [[7, 1, 6], [8, 4, 4]]
    ]
)

In [108]:
tensor_1

tensor([[[1., 2., 3.],
         [5., 4., 7.]],

        [[4., 3., 8.],
         [1., 8., 4.]],

        [[7., 1., 6.],
         [8., 4., 4.]]])

In [109]:
tensor_1.device

device(type='cpu')

In [110]:
# new_tensor = tensor_1.to('cpu') pas disponible sur MacOS

In [111]:
tensor_1.shape

torch.Size([3, 2, 3])

`torch.Size([3, 2, 3])` represents the dimensions/shape of a 3-dimensional PyTorch tensor:

- First dimension (3): The tensor has 3 layers/slices
- Second dimension (2): Each layer has 2 rows
- Third dimension (3): Each row has 3 elements

So the tensor is organized as:
- 3 layers
- Each layer contains 2 rows
- Each row contains 3 elements

In [112]:
print("shape[0] =", tensor_1.shape[0])
print("shape[1] =", tensor_1.shape[1])
print("shape[2] =", tensor_1.shape[2])

shape[0] = 3
shape[1] = 2
shape[2] = 3


Dans notre tensor `tensor_1`, la forme (shape) est expliquée comme suit:

- `shape[0] = 3` signifie que le tensor a 3 couches/matrices
- `shape[1] = 2` signifie que chaque couche contient 2 lignes
- `shape[2] = 3` signifie que chaque couche contient 2 valeurs
Pour mieux visualiser cette structure, voici une cellule qui affiche les couches séparément:

Comme on peut le voir:
- Il y a 3 couches (shape[0] = 3)
- Chaque couche contient 2 lignes (shape[1] = 2)
- Et chaque ligne contient 3 valeurs (shape[2] = 3)

In [113]:
print("Rank =", len(tensor_1.shape))
print("Number of elements =", tensor_1.numel())

Rank = 3
Number of elements = 18


Le résultat s'explique simplement:

- **Rank = 3**: Notre tenseur a 3 dimensions (c'est le nombre de crochets imbriqués `[[[...]]]`), donc son rang est 3
- **Number of elements = 18**: C'est le produit des dimensions: 3 x 2 x 3 = 18
  - 3 couches
  - 2 lignes par couche
  - 3 éléments par ligne
  - Donc au total: 3 * 2 * 3 = 18 éléments dans le tenseur


In [114]:
tensor_1[0] # acceder a un tensor precis

tensor([[1., 2., 3.],
        [5., 4., 7.]])

In [115]:
tensor_1[0, 1, 0]
tensor_1[1:2]
tensor_1[2]

tensor([[7., 1., 6.],
        [8., 4., 4.]])

Pour accéder à des éléments spécifiques d'un tenseur PyTorch, vous pouvez utiliser l'indexation. Voici les différentes façons :

L'indexation fonctionne comme suit:
- `tensor[i]`: accède à la i-ème couche
- `tensor[i,j]`: accède à la j-ème ligne de la i-ème couche  
- `tensor[i,j,k]`: accède à l'élément à la position (i,j,k)
- `tensor[i:j]`: slice qui sélectionne les couches de i à j-1


In [116]:
torch.ones(4, 2, 3) # 4 nb lot, 2 nb lignes, 3 nb valeurs torch.ones = 1

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [117]:
torch.zeros(4, 2, 3) # same previous but with 0

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [118]:
torch.ones_like(tensor_1) # reprend shape tensor_1 avec 1 seulement via like

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [119]:
torch.zeros_like(tensor_1)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [120]:
torch.randn(2, 3 ,5)

tensor([[[ 0.3494,  0.8644,  0.8153, -0.0106, -1.3720],
         [ 0.6143,  0.0051,  0.9567,  0.0178, -1.0133],
         [-0.8733, -2.0999, -1.5151,  0.1248,  0.8042]],

        [[-1.6620,  1.4787, -3.3398,  0.4656,  1.3256],
         [-0.9545,  0.0884,  0.1998, -0.3490, -0.9207],
         [-2.2086, -0.8180, -0.2373, -0.3553, -0.1711]]])

In [121]:
torch.rand_like(tensor_1)

tensor([[[0.9062, 0.9338, 0.3255],
         [0.5686, 0.2389, 0.2556]],

        [[0.4454, 0.8843, 0.5334],
         [0.7385, 0.2101, 0.7977]],

        [[0.9585, 0.9066, 0.9895],
         [0.1840, 0.2599, 0.4201]]])

In [122]:
torch.rand(2, 3 ,5, device='cpu')

tensor([[[0.3271, 0.9386, 0.2212, 0.0015, 0.4428],
         [0.6145, 0.0700, 0.8782, 0.0713, 0.8542],
         [0.7221, 0.2118, 0.6146, 0.4210, 0.1671]],

        [[0.3568, 0.9780, 0.7004, 0.7773, 0.7649],
         [0.4950, 0.7340, 0.0710, 0.2750, 0.1926],
         [0.3609, 0.0543, 0.5986, 0.0019, 0.4732]]])

In [123]:
tensor_1

tensor([[[1., 2., 3.],
         [5., 4., 7.]],

        [[4., 3., 8.],
         [1., 8., 4.]],

        [[7., 1., 6.],
         [8., 4., 4.]]])

In [124]:
tensor_edit = (tensor_1 - 1) * 2
tensor_edit

tensor([[[ 0.,  2.,  4.],
         [ 8.,  6., 12.]],

        [[ 6.,  4., 14.],
         [ 0., 14.,  6.]],

        [[12.,  0., 10.],
         [14.,  6.,  6.]]])

In [125]:
print("Mean:", tensor_1.mean())
print("Stdev: ", tensor_1.std())

Mean: tensor(4.4444)
Stdev:  tensor(2.4307)


In [126]:
tensor_1.mean(1) # mean dimension 1

tensor([[3.0000, 3.0000, 5.0000],
        [2.5000, 5.5000, 6.0000],
        [7.5000, 2.5000, 5.0000]])

In [127]:
import torch.nn as nn

In [128]:
linear = nn.Linear(10, 2)
example_input = torch.randn(8, 10)

In [129]:
example_input

tensor([[-2.2051,  0.2674,  0.3781, -1.2451,  0.1667,  1.5251,  0.3019, -2.2290,
         -0.4814, -0.2293],
        [-1.5956, -0.3460, -0.4435,  0.3425,  1.2652, -0.0120,  0.3418,  0.3230,
          2.6629, -0.0492],
        [-1.7680, -0.4319,  0.7675, -0.4919,  1.4065,  0.5956,  0.8353,  1.4992,
          0.7363,  0.4763],
        [-0.8357, -0.3124,  1.0507, -1.5102,  1.3204, -1.2812, -0.6702, -0.3847,
         -0.0523,  1.8883],
        [ 0.4629, -1.3002,  2.4384,  0.6510,  0.4541,  1.0741, -1.1369,  0.5594,
         -0.0225,  0.0119],
        [-0.7421,  0.0384,  0.9780,  0.6906,  0.6514, -0.0509,  1.2801, -0.7379,
          0.5032,  0.8741],
        [ 2.1027,  1.7619,  0.3265, -2.3665,  1.0622,  1.2155, -3.3445, -0.4638,
          0.1355,  0.6326],
        [-0.5763,  0.8958,  2.2230, -0.0866, -0.6375, -0.7388, -0.4615,  0.5599,
         -0.4980,  0.6614]])

In [130]:
exemple_output = linear(example_input)

In [133]:
print(exemple_output)

tensor([[ 1.0597, -0.1339],
        [ 1.2756, -1.5828],
        [ 0.6252, -1.8062],
        [ 0.3906, -1.3659],
        [-0.3220, -1.2232],
        [ 1.2837, -0.4234],
        [ 0.0811, -0.7438],
        [-0.1561, -0.3580]], grad_fn=<AddmmBackward0>)


In [135]:
relu = nn.ReLU()
relu_output = relu(exemple_output)
print(relu_output)

tensor([[1.0597, 0.0000],
        [1.2756, 0.0000],
        [0.6252, 0.0000],
        [0.3906, 0.0000],
        [0.0000, 0.0000],
        [1.2837, 0.0000],
        [0.0811, 0.0000],
        [0.0000, 0.0000]], grad_fn=<ReluBackward0>)


In [137]:
batchnorm = nn.BatchNorm1d(2)
batchnorm_output = batchnorm(relu_output)
print(batchnorm_output)

tensor([[ 0.9032,  0.0000],
        [ 1.3179,  0.0000],
        [ 0.0687,  0.0000],
        [-0.3820,  0.0000],
        [-1.1323,  0.0000],
        [ 1.3335,  0.0000],
        [-0.9766,  0.0000],
        [-1.1323,  0.0000]], grad_fn=<NativeBatchNormBackward0>)


In [138]:
mlp_layers = nn.Sequential(
    nn.Linear(5, 2),
    nn.BatchNorm1d(2),
    nn.ReLU(),
)

In [139]:
test_example = torch.randn(5, 5) + 1
print("Input:")
print(test_example)
print("Output:")
print(mlp_layers(test_example))

Input:
tensor([[ 1.3184,  2.3107, -0.8534,  0.2868,  2.4706],
        [ 2.1967,  2.0083, -0.4471,  2.6184, -2.6111],
        [ 0.3873,  0.3814,  0.8839, -0.7964, -0.8461],
        [ 2.1061,  2.9417,  3.5428,  0.6411, -0.9482],
        [ 2.1812,  0.6491,  1.6579,  0.7018,  1.2200]])
Output:
tensor([[0.0000, 0.0000],
        [0.0000, 1.8675],
        [0.8662, 0.0000],
        [0.6400, 0.0000],
        [0.8664, 0.0000]], grad_fn=<ReluBackward0>)


In [140]:
import torch.optim as optim
adam_opt = optim.Adam(mlp_layers.parameters(), lr=1e-1)

In [142]:
train_example = torch.randn(100, 5) + 1
adam_opt.zero_grad()

cur_loss = torch.abs(1 - mlp_layers(train_example)).mean()

cur_loss.backward()
adam_opt.step()
print(cur_loss)

tensor(0.7368, grad_fn=<MeanBackward0>)


Cette cellule effectue une étape d'entraînement d'un réseau de neurones MLP (Multi-Layer Perceptron). Voici le détail des opérations:

1. `train_example = torch.randn(100, 5) + 1` 
   - Crée un tenseur d'entrée de 100 exemples avec 5 caractéristiques chacun
   - Les valeurs sont aléatoires (distribution normale) + 1

2. `adam_opt.zero_grad()`
   - Réinitialise les gradients à zéro avant la passe arrière

3. `cur_loss = torch.abs(1 - mlp_layers(train_example)).mean()`
   - Calcule la perte (loss) en:
     - Passant les données dans le MLP (`mlp_layers(train_example)`)
     - Soustrait le résultat de 1
     - Prend la valeur absolue
     - Calcule la moyenne

4. `cur_loss.backward()`
   - Calcule les gradients par rétropropagation

5. `adam_opt.step()`
   - Met à jour les poids du réseau en utilisant l'optimiseur Adam

Cette cellule fait partie d'une boucle d'entraînement typique en deep learning:
1. Forward pass (propagation avant)
2. Calcul de la perte
3. Backward pass (rétropropagation)
4. Mise à jour des poids

L'objectif est d'ajuster les paramètres du réseau pour que sa sortie se rapproche de 1 pour les données d'entrée.


In [144]:
test_leo = torch.randn(100, 5) + 1 # creer base test

adam_opt.zero_grad() # remettre les gradients à 0

cur_loss = torch.abs(1 - mlp_layers(test_leo)).mean() # calculer la moyenne de la perte .abs pour valeur absolue,

cur_loss.backward()

adam_opt.step()

In [148]:
print(mlp_layers(test_leo))

tensor([[0.0000, 0.1830],
        [0.5243, 0.2590],
        [0.0000, 0.0000],
        [0.3276, 0.6477],
        [0.0000, 0.0000],
        [0.0000, 0.9575],
        [1.2655, 0.0000],
        [0.0000, 1.1881],
        [1.0796, 0.0000],
        [0.0000, 0.4401],
        [0.1781, 0.0341],
        [0.2317, 0.0000],
        [0.1566, 0.0000],
        [1.4588, 0.0000],
        [0.0000, 0.0000],
        [0.2393, 0.0000],
        [0.0000, 0.4881],
        [0.0489, 0.0000],
        [0.0566, 1.9528],
        [1.5021, 0.0000],
        [0.0463, 0.0000],
        [0.4627, 0.0000],
        [0.2252, 0.9024],
        [1.9774, 0.0000],
        [0.0000, 0.8230],
        [1.1288, 0.0000],
        [0.9166, 0.0000],
        [0.1731, 0.3542],
        [0.0413, 0.0000],
        [0.0000, 1.0121],
        [0.4455, 0.3047],
        [0.1134, 0.0000],
        [0.0000, 1.0086],
        [0.8958, 0.7062],
        [0.0000, 0.0000],
        [0.0000, 0.2057],
        [0.9673, 0.1911],
        [0.0000, 1.2249],
        [0.0

In [149]:
list(mlp_layers.parameters())

[Parameter containing:
 tensor([[ 0.0582, -0.4204, -0.0171, -0.0495,  0.2783],
         [-0.1141,  0.4752, -0.5387,  0.1279, -0.0122]], requires_grad=True),
 Parameter containing:
 tensor([-0.2993, -0.1011], requires_grad=True),
 Parameter containing:
 tensor([0.7473, 0.7460], requires_grad=True),
 Parameter containing:
 tensor([0.0412, 0.0507], requires_grad=True)]